# Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.html
  - about/about.html
  - contact/contact.html

footer: '<a href="https://www.0dayprotection.com/">Download</a>'

style: dark
listen_for_clients_preferred_style: false

plugins:
  - jekyll-seo-tag

remote_theme: 0dayprotect/jekyll-themed-console
