# Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

footer: '<a href="https://0dayprotection.com/">Download</a>'

style: dark
listen_for_clients_preferred_style: false

plugins:
  - jekyll-seo-tag

remote_theme: 0dayprotect/jekyll-themed-console
